### ISSUE TITLE
Gate on Ildaeil Host Input does not match MIDI Gate inside loaded plugin (ie, Cardinal itself)

### ISSUE THREAD

**Issue by jp-gorman** [DISTRHO/Cardinal#106]
Scenario:
-------------
Load cardinal Host as a module within cardinal
Add Cardinal Synth as the module into the host (to get cardinal within cardinal)
Pass any signal to the host input "gate"

Expected
----------
Expected to see the gate signal received in the "from device" inner Cardinal Synth

Actual
----------
Inner Cardinal Synth "from device" gate does not appear to get this signal and shows 0

**Comment by falkTX** [comment]
correct. that "gate" is for MIDI input, not direct device usage.

It is a bit confusing for now, but soon enough the Ildaeil will not have MIDI input CVs and rely on an expander module to provide that funcionality (and thus also be able to automate parameters or do MIDI out the same way).

Confusing for now because the expander is not done yet. WIP pull request still open about this.

**Comment by falkTX** [comment]
Latest version no longer has ildaeil with dedicated midi ports.
In order to have those we need to use an expander, which is clearly labelled as MIDI.
So I consider this issue resolved, hopefully it is less confusing this way.

PS: later on a cardinal-within-cardinal dedicated module will be added, but wont be there for the initial release
