### ISSUE TITLE
Official VCVRack V2 appears to be open source and free?

### ISSUE THREAD

**Issue by zynmuse** [DISTRHO/Cardinal#114]
It could be that this was not the case . However I have recently forked and compiled the originator's version and it works fine on my linux PC and comes with hundreds of free plugins via their library.
This appears to contradict your README file.

**Comment by falkTX** [comment]
Where exactly? I mention Rack Pro, this is a commercial proprietary product, and that Rack itself is free.

Also, the online library only has linux/mac/win intel 64bit binaries, there is no support for BSD systems, ARM architecture or anything like that.
So for those platforms you need to build plugins anyway

**Comment by falkTX** [comment]
Also, forking and redistributing vcvrack as-is is not allowed, you need to either replace or hide the VCV logo from their artwork (the license states the VCV logo is not allowed on derivates works, which a fork counts as).
Good luck doing that while the original artwork is also CC-ND (non-derivatives) so you are not allowed to change the artwork ;)

**Comment by dromer** [comment]
> This appears to contradict your README file.
The README very clearly states the `plugin` version.

Also you don't need to `fork` a project in order to build it. I think you mean `clone` ?

**Comment by zynmuse** [comment]
dromer - Yes I did mean clone!
falkTX - I was frustrated to see negative comments (in your README) regarding software that was freely available for anyone to download and compile.
The original is clearly an excellent piece of software and appears to be well received. 
I assume the originator of the code ( Andrew Belt) is happy for you to copy and use his software in this way. I assume you will have spoken with him about this. From the README I got the impression that you have not! perhaps you can clarify.

**Comment by falkTX** [comment]
Yes I did, though I am not sure what is there to clarify.

Can you describe what your questions/doubts around the project after fully reading the readme?
There are no personal attacks in any way in there, mostly only technical explanations

**Comment by dromer** [comment]
The Rack Pro plugin is not free and opensource, which is what some of us do want.
Also we don't copy the code (in the sense that we use upstream repositories directly).

And of course we want VCV Rack to succeed, because without it Cardinal wouldn't exist!
The official Pro plugin has many features that Cardinal doesn't have, and vise-versa. They should be able to co-exist peacefully and serve different goals and purpose.

We just want to have a proper opensource plugin version of Rack, which the closed Pro version does not offer.

**Comment by zynmuse** [comment]
Thank you for  your responses.
Firstly I did make a mistake in my comparison since I hadn't realised the pro version of Rack was a plugin. What I cloned was the source code for the stand alone version - which is complete and simple to compile on Linux.

Checking the Rack source code and the website I can find no reference to any software license for the Rack only for the commercial modules. 

I guess the Cardinal plugin will continue to work while the Rack code is still present on Github?

**Comment by falkTX** [comment]
> Checking the Rack source code and the website I can find no reference to any software license for the Rack only for the commercial modules.

It is quite clear from https://github.com/VCVRack/Rack/blob/v2/LICENSE.md in my opinion

> I guess the Cardinal plugin will continue to work while the Rack code is still present on Github?

Yes, though I have setup a mirror that keeps code online in worst case Rack is deleted or something
https://git.kx.studio/VCVRack/Rack/src/branch/v2

Closing this ticket since it is not an actual issue then.
If more needs to be said, please use the github discussions area for that.
