### ISSUE TITLE
Host Audio: Left/Mono channel behavior is unexpected / different from VCV Rack

### ISSUE THREAD

**Issue by bambax** [DISTRHO/Cardinal#204]
Left channel is mono when nothing is connected to the right channel: when only left channel is receiving something, audio comes out of both channels, and it's apparently not possible to have a silent right channel without connecting something to the right channel. This is different from VCV Rack / Audio8 where odd channels are left only, and even channels right only.

If that's indeed the desired approach, then maybe a couple of words of explanation may help? (hover text only says "#1 input").

The UI is also a little confusing; the big "level" knob looks too much like a pan control, and the levels above it display intensity for both channels. Not sure if a level control is needed here.

**Comment by falkTX** [comment]
Have you used the audio2 modules from VCVRack? That is how the Host-Audio2 module from Cardinal works, it copies its behaviour.
You can use Host-Audio8 from Cardinal if you prefer that approach similar to what you describe.

**Comment by falkTX** [comment]
Just tested with latest builds, all is working as intended. The left signal is copied to the right if only left is connected, just as audio2 on VCV Rack. The level knob and meters show left/mono and left+right and right, working also as intended.
So this is purely confusion on how things work I guess.

The default patch on Cardinal uses audio2, because the stereo plugin variant is likely the one most often used.

**Comment by bambax** [comment]
Yes ok you are right, this works the same as VCV Rack Audio2 / Audio8, but the confusion comes from the fact that Audio2 is loaded by default in Cardinal, and in VCV Rack all I ever used was Audio8.

It may be better to default to Audio8 though? as it would help to show one can have more than 2 in/out audio channels.

But anyway, yes, all is working fine. Sorry for this.
