### ISSUE TITLE
Module Request: WhatTheRack

### ISSUE THREAD

**Issue by fotisandstuff** [DISTRHO/Cardinal#216]
https://github.com/korfuri/WhatTheRack

These randomizers are under WTFPL License. Could they be implemented in Cardinal?

**Comment by dromer** [comment]
Lol @ "VCV Rack is missing an essential part of modular synthesis, that is, puzzling over someone else's rack."

Would love to add these and will have a go at this soon. The code should be fine (I think), however the font that is used doesn't seem to have a proper license and currently includes things like a pdf and other promo material. We need this to be a proper open content distributable in order to include it into a release. Possibly an alternate font needs to be found if we can't find a proper license for this.

**Comment by fotisandstuff** [comment]
Great! Btw Cardinal is in Patchstorage's "platform requests". Let's give it all the "hearts" it deserves <3 https://patchstorage.com/requests/cardinal/

**Comment by dromer** [comment]
I've added a [WIP] pull request. Still some things to sort out and fix, but it generally seems to work at least: https://github.com/DISTRHO/Cardinal/pull/218

**Comment by falkTX** [comment]
Has been added to latest builds.
Needed a little fix for v2.1 stuff, patch sent upstream in https://github.com/korfuri/WhatTheRack/pull/8
