### ISSUE TITLE
-fno-gnu-unique flag should be set not based on OS but based on compiler, and clang doesn't know about it

### ISSUE THREAD

**Issue by yurivict** [DISTRHO/Cardinal#237]
clang fails because of this flag.

Many places in code set this flag for non-MacOS and non-Windows. This is wrong - it should be based on compiler.

clang-12 on FreeBSD 13

**Comment by falkTX** [comment]
Detecting this is not as easy as it might seem.. clang likes to pretend and be gcc compatible, at least on linux.
Since I know you mostly just want this for compatibility with BSD, I made it so that in cardinal, carla and dpf, `-fno-gnu-unique` is skipped if using bsd.
That should fix things for your side.
Let me know if not the case, I will then reopen the ticket.
