### ISSUE TITLE
MIDI-CV device doesn't recieve any clock data from DAW

### ISSUE THREAD

**Issue by vcvrackideas** [DISTRHO/Cardinal#25]
So CLK and CLK\N outputs don't produce any data if transport is in play mode. 
However CV-MIDI device works nicely in case if need send a sequence to any other synth in ableton (another track in routing menu), and that's very nice!

**Comment by falkTX** [comment]
Implemented start, stop and continue.
For the clock pulses I am simply not going to do it, the way MIDI-CV module is handling timing - basically triggering 0xF8 MIDI Clock Pulse signals - is something I consider legacy silliness.
Even the MIDI association knows they are troublesome, and why MIDI 2 introduces extra timing information so those pulses can be made more accurate.
Also, it would be a bit tricky to implement due to needing to mix/interleave host MIDI events with ones created by us based on host timing.
Not to mention that converting host time to MIDI and then to CV is quite awkward to work with.

We have a dedicated panel for host-time information, so let's just use that instead.

In order to not lead into confusion I have made the CLK and CLK/N not visible on the MIDI-CV module.

![image](https://user-images.githubusercontent.com/1334853/146657430-abfcbd6f-0645-47a3-a117-3181622e6606.png)

Perhaps not the best approach, but for an initial release I think it is quite fine.
And with this I close the ticket.
