### ISSUE TITLE
Multi-thread incompatibility?

### ISSUE THREAD

**Issue by antoineportes** [DISTRHO/Cardinal#295]
I'm using the LV2 version of Cardinal ("regular" — i.e. not FX nor Synth) in Reaper under windows 10 with an AMD Ryzen 7 3700 (8 cores, 16 threads) processor.

Everything works perfectly (multi-channel midi in/output, host parameter modulation, sidechain audio in/out, 16x oversampling, etc.) except for the fact that the performance meter in Cardinal always shows a CPU usage 16 times higher than the one in Reaper (67.5% vs 4.2% with my current patch).
I've loaded the same patch in the VST3 version and got the same issue.

I'm guessing that Cardinal sticks to 1 of the 16 threads, which highly limits its potential (and/or prevents me from oversampling it).

Am I right? And is there any solution?

![Cardinal+Reaper CPU usage](https://user-images.githubusercontent.com/25763261/178452059-cac18719-4c06-4368-bb0f-94a85b595563.png)

**Comment by falkTX** [comment]
This is intentional. Cardinal will use the host audio thread and nothing more (except for background threads for stuff like disk streaming or plugin scanning in some DISTRHO modules).
It is unwanted to spread modules into multiple threads for processing.
If this is something you need, let the host handle that for you which will always do a better job at it - that is, instead of one big cardinal patch, just have smaller ones but spread around multiple DAW tracks.

**Comment by antoineportes** [comment]
Ok thanks! I thought of using multiple instances on the same track as a workaround, but the inability to feedback across them was still unsatisfying. Spreading them over multiple tracks should solve this indeed.

Thanks for the tip and the quick answer!
