### ISSUE TITLE
Custom GUI missing with Studio One 5 using VST3

### ISSUE THREAD

**Issue by tinner-t** [DISTRHO/Cardinal#303]
its tarting i studio one but i dont see the rac
![DDD](https://user-images.githubusercontent.com/75805400/178697403-26ce0e6c-feea-43bd-b47f-85943d0bdd5d.jpg)
k

**Comment by falkTX** [comment]
Is this VST2 or VST3? if using vst3, try the vst2 version

**Comment by woolyninja** [comment]
I came in here to ask the same thing. Thanks to @falkTX's comment I uninstalled and reinstalled leaving the VST3 out for now (since its experimental). Then in Studio One (Windows) I had to go into Studio One > Options > Locations > VST Plugins > Add... and I added C:\Program Files\Common Files\VST2 (the default install location). It found the plugin and it loads in fine now.

Thanks!

**Comment by tinner-t** [comment]
YESSSSSSSSSS its work with to add C:\Program Files\Common Files\VST2  :)    Thx

**Comment by tinner-t** [comment]
VST3 dont work but Vst2 works fine :)

**Comment by falkTX** [comment]
VST3 latest build works, I confirmed it myself.
