### ISSUE TITLE
AUDIO 8

### ISSUE THREAD

**Issue by steveparkerdj** [DISTRHO/Cardinal#320]
i can't seem to find a way to output on the cardinal host audio apart from ch1 + ch2
theres no where in my Ableton mixer to select the individual outputs or inputs.

i tried with all vst2 vst3 and AU, mac catalina, intel, ableton live 11
![Screenshot 2022-07-17 at 14 19 31](https://user-images.githubusercontent.com/105745595/179400334-7366a012-dfc3-4592-942d-4d9fe006c82c.png)

**Comment by dromer** [comment]
Cardinal FX and Cardinal Synth only have stereo i/o, the full Cardinal (LV2 and VST3) has all 8 i/o, however not all hosts can actually use those.

**Comment by steveparkerdj** [comment]
I can't event open the full Cardinal on Ableton

**Comment by steveparkerdj** [comment]
I know Softube Modular can achieve that with AU and if not mistaken voltage as well. 
I see in VST3 the Cardinal but when I open it I get an empty insert plugin.

**Comment by steveparkerdj** [comment]
here ..
![ ](https://user-images.githubusercontent.com/105745595/179403083-b9732431-10f2-4b93-a48b-31376794c9f9.png)
.

**Comment by steveparkerdj** [comment]
Any reason why my DAW doesn't recognize Cardinal full?

**Comment by falkTX** [comment]
Because VST3 is experimental and this is one of the parts of it.
I need to properly implement optional buses and speaker layouts on the VST3 plugin stuff first, Ableton refuses to load the plugin otherwise. For the FX and Synth variants the audio ports are simply tagged as stereo pair, so Ableton is happy enough to accept them. The main variant is more complex, and has CV ports too.
Will properly implement this later.

**Comment by steveparkerdj** [comment]
Thanks :) would be awesome ...

**Comment by falkTX** [comment]
this one is also fixed in 22.11, right?

**Comment by steveparkerdj** [comment]
Yes fixed
