### ISSUE TITLE
Only mono output when used as effect in FL Studio

### ISSUE THREAD

**Issue by SigmaDee** [DISTRHO/Cardinal#340]
When I put Cardinal as an effect in FL studio I get only mono output even though I can verify that there are different signals on the right and left into Cardinal and out of Cardinal.

If I just route the signal from Left out to Left in and Right out to Right in, only the left signal will be heard in both left and right channel at the output.

![bild](https://user-images.githubusercontent.com/3245351/182030658-e2204a78-d97f-438a-9595-6708ac445009.png)
![bild](https://user-images.githubusercontent.com/3245351/182030675-2922a2de-d348-49dc-89f2-e2eb58b473fb.png)
![bild](https://user-images.githubusercontent.com/3245351/182030681-c0101672-0504-4126-96a8-f939d84da9df.png)

**Comment by grimeyboiii** [comment]
I'm pretty sure it is because how Cardinal handles the stereo signals.
Pleas have in mind that you can obtain three different mono signals from a stereo one by **1)** duplicating the left, **2)** the right and **3)** phase-cancelling both.
Since _left_ signal has priority within the plugin (as physical modular synths I guess), if there's no incoming _right_ signal, the plugin grabs the _left_ and duplicates it to create a virtual™ right signal*, which played together gives a mono (and if the right signal exists and is slightly different than the left one, the sum gives an stereo signal); instead of phase-cancel the left and the polarity-inversed right signal (which gives you the **MID mono** signal and is the most common way DAWs work when adjusting the width of the stereo field, IIRC).

So, if you hard pan the signal before it gets into Cardinal, you'll always get the results you observe, particularly if you feed Cardinal FX with a mono signal.

If you want to pan signals, I suggest you to do it inside Cardinal FX or after it in the effects chain.

*About the virtual™ right signal, I think that workflow was thought as it is in order to integrate mono devices into stereo workflows. Otherwise, it might be quite awkward to hear a hard and nice hitting bassline only at the _left_ side of the club.

**Comment by SigmaDee** [comment]
Thanks for your answer.

Actually, I have a stereo signal into cardinal and all the way to the Host Audio output. I will provide an example with a VU-meter inside Cardinal too to show the issue. Will try tonight when I'm off work.
The right signal only disappears (is replaced by the left) at the interface back to the DAW. As you can see in the figures above I have both signals just passed through from Audio 1 out to Audio 1 in and from Audio 2 out to Audio 2 in.

However I pan it within cardinal, only the left signal will appear on both the left and right inputs to the DAW.

Maybe I'm misunderstanding the Host Audio interface. Is Audio 1 supposed to carry the left and Audio 2 the right signal, or are both stereo channels and could be split somehow in Cardinal?

**Comment by dromer** [comment]
Indeed Audio 1 should be left and Audio 2 right.

There is also the stereo Host Audio module which will turn a mono signal to stereo when only the left input is connected.

**Comment by SigmaDee** [comment]
I got the same behaviour with the Stereo Host Audio module.

**Comment by dromer** [comment]
You actually never said which plugin format or operating system you are using.

Can you give more details about your system and cardinal version?

**Comment by SigmaDee** [comment]
I just happened to notice today that in the effect plugin selector there were two VST3 versions of Cardinal.

![bild](https://user-images.githubusercontent.com/3245351/185256050-1b63bf88-da30-40f4-8500-441135404bea.png)

The one named "Cardinal FX" works exactly as one would expect, while the one named "Cardinal" takes a stereo input and processes in stereo all the way through, but outputs the left channel on both outputs.

My only guess is that this is some sort of workaround for FL Studio. Anyway, I'm all good now. Thanks for your help and thanks for an awesome synth and effect plugin.

And since you asked:

![bild](https://user-images.githubusercontent.com/3245351/185256555-b9c919fc-1412-4ac0-af36-6c77aa193256.png)

I'm on Windows 10 Pro.

**Comment by falkTX** [comment]
The main vst3 variant is not working so well regarding buses.
I added in a few things on the latest builds (not yet in a release) but did not check with FLStudio.

VST3 and its bus/aux/speaker system stuff is quite annoying and a mess to deal with. It is 1 of 3 remaining issues to fix before calling VST3 version stable (the other 2 are timing info and CV support)

**Comment by dromer** [comment]
thnx! ok yes FX is meant to use as an insert, it is for hosts that require a specific port configuration. There is also the Synth (also two i/o and not visible here, for use as an instrument "VSTi") and the VST3 which has 8 audio i/o and 10 cv i/o (cv not visible in most hosts. audio i/o needs some work on VST3 for some hosts as well)
