### ISSUE TITLE
Request: Oddsound Modules.

### ISSUE THREAD

**Issue by Andreya-Autumn** [DISTRHO/Cardinal#404]
Hello! And thanks for the hard work on this, it's super sweet! :) 

So yeah, ODDsound have some modules to use their fantastic MTS-ESP system. Most important of which is their v/oct quantizer. 

If you don't know about the system there's more info on oddsound.com, but long story short: it's a clever open-source standard for managing musical tuning across an entire electronic music environment. 
Every compatible software or hardware instrument connects behind the scenes to a "master" tuning plugin, which can adjust the tuning of all of them simultaneously in real-time.

The previously most established ("micro")tuning workflow was using text files with scale scale and keyboard mapping info. The MTS-ESP system offers two advantages: 1,it saves time to tune all instruments from one central place instead of loading .scl and .kbm files into every single instance. And 2, the tuning of any note in the scale can be adjusted during playback which is very useful and opens up some really interesting creative possibilities.

It'd be great to have the ODDsound modules in Cardinal!

Here's the github repo for the modules: https://github.com/ODDSound/MTS-ESP-VCVRack 
Oli who develops these is usually very happy to answer questions if necessary.

Thanks again!

**Comment by falkTX** [comment]
Module requests should go to https://github.com/DISTRHO/Cardinal/wiki/Possible-modules-to-include
ODDSound is already listed there, with a note for issues with these modules. Basically the MIDI stuff would need to be reimplemented in order to work in Cardinal.
Best to do a request for ODDSound authors to bring their modules to Cardinal, or try to find someone to do the porting process work.

**Comment by Andreya-Autumn** [comment]
Should've checked that first shouldn't I? My bad, sorry! ;)

I'm happy to reach out to Oli about it. Let me just ask some clarifying questions first so I can better understand what to ask.

I read "Uses midi and needs a master plugin for quantization" on that list you linked. It's not perfectly clear to me why or how that's a problem?

The MIDI plugins in the ODDsound repo are identical to the stock VCV MIDI converters except with added MTS-ESP compatibility. Would it maybe be a more sensible request to just implement the MTS-ESP compatibility directly in the Cardinal Host MIDI module? 

(For the record, when the master plugin is not present the MTS-ESP system is totally out of the way. It's built to default back to standard 12-TET @ A=440hz. Maybe that was clear to you, disregard this if so. Some other devs I've had this conversation with have been nervous about that so I figured it may be worth clarifying)

**Comment by falkTX** [comment]
the wiki description is a bit cryptic yeah.
only real issue is that a reimplementation of the midi stuff is required, as this is one part where cardinal does not follow vcv rack.

on vcv rack:
- midi is handled by rtmidi
- has direct access to hw, via rtmidi
- runs on separate threads with a queue for dispatching stuff to main/audio thread
- provides classes for plugins/module to reuse and implement their own native/hw midi modules

on cardinal:
- midi is handled internally on a custom API (does not use rtmidi)
- is only provided by the host, no direct midi hw access
- runs on the main/audio thread directly, without queues
- does not expose the APIs for other plugins/modules to use (but we can correct this one)

Here is an example of Cardinal custom API in action: https://github.com/DISTRHO/Cardinal/blob/main/plugins/Cardinal/src/HostMIDI-Gate.cpp#L57 (look for `// Cardinal specific` code comments.

Additionally to this, Cardinal also has a concept of "terminal modules".
These are special modules that always run at the start and end of the audio processing chain.
So, for example, the MIDI-to-CV module can query the available MIDI messages before all other modules run, ensuring lower latency. And at the same time it will run again at the end of the processing chain, ensuring and events it received are sent to the host on that same audio cycle. This minimizes latency when using "terminal" modules.

VCV Rack has a sorta similar context, with 1 (and only 1) module being able to be "master" that runs before and after all other modules. MIDI hw modules are not included, so there is latency and jitter all around when using them

**Comment by eventual-recluse** [comment]
I know this issue is closed, but I've been having a go at this.

So far I have the HostMIDI module working with MTS-ESP after including libMTSClient.h and libMTSClient.cpp, and adding just a few lines of code from MTS-ESP-VCVRack.

I'm still testing it out, but the updated HostMIDI.cpp here for now in case it's of any use:

https://github.com/eventual-recluse/Cardinal-MTS-ESP-Support

**Comment by dromer** [comment]
For MTS support in Cardinal we would prefer to use a different MTS-ESP library.
There is work for an opensource implementation here: https://github.com/baconpaul/mts-dylib-reference

**Comment by falkTX** [comment]
> For MTS support in Cardinal we would prefer to use a different MTS-ESP library.

its more than that, the "official" MTS library is simply unusable. the provided binaries only support a very specific set of systems (only x64 on linux, no bsd, no win32) and anyhow there is no source code for these provided binaries which means we cant use them.

the code from mts-dylib-reference uses C++17 which is higher than C++11 minimum deps from Cardinal.

so unless there is some other lib, we will need to roll our own implementation. but it can be based on mts-dylib-reference

**Comment by falkTX** [comment]
correction: if all you want to use are the MTS client APIs and not be active as "master", then your current approach should already work.

**Comment by dromer** [comment]
Oh right, there's the client-v-master separation. and I didn't know about mts-dylib-reference minimum requirements .. hmm

**Comment by eventual-recluse** [comment]
Yes, the changes I've made only need the MTS Client parts (the code for which is 0BSD licensed as far as I'm aware). Apart from the inclusion of libMTSClient.h and libMTSClient.cpp, there are just a few lines of code to add to HostMIDI.cpp to get that module working nicely with continuous tuning.

In any case, I am happy enough that I can build a MTS-ESP capable Cardinal for myself, but hopefully others can have that option in the future as well.

I was going to try to do it as an extra plugin but it's a bit beyond me right now... whereas adding a few changes to HostMIDI.cpp is straightforward.

**Comment by falkTX** [comment]
We could probably see about which parts of the cpp file are needed and import those, since you are only using 2 calls from it I guess we dont need the full thing.

What would be the simplest way to test that this is working?

**Comment by eventual-recluse** [comment]
For testing you'd need MTS-ESP be set up on your system with a master plugin and all that... so

1. Install libMTS (sorry...) https://github.com/ODDSound/MTS-ESP#libMTS
2. Get a MTS-ESP master plugin (I usually use SurgeXT synth as a MTS-ESP master).
3. Load Cardinal built with the changes, & also load the master plugin (I've been using the master plugin and Cardinal VST3 in a DAW).
4. Check the notes change when you change the master tuning. You could also reference the changes against a synth like Surge to check the note changes are the same.

I think that's probably the easiest way... which I realise is a bit of a palaver. Or ask for some MTS-ESP users to test it out... the SurgeXT discord comes to mind

**Comment by eventual-recluse** [comment]
PS I think mts-dylib-reference is a replacement for libMTS from ODDSound? In that case, it should not matter that it builds with C++17 as you would never need to include it in Cardinal at all, even if you made some kind of 'master' module inside Cardinal.

It's an external library that's built completely separately and installed on the user's OS. It's not included inside any master or client plugins.
