### ISSUE TITLE
Adding the SurgeXT collection

### ISSUE THREAD

**Issue by jpotier** [DISTRHO/Cardinal#412]
It seems that the soon-to-be-stable SurgeXT collection could be part of the set of VCV modules bundled with Cardinal, as they should have a compatible license: https://github.com/surge-synthesizer/surge-rack.

This is a request for adding them. I don't have time to do it right now myself, but I'll probably get to it if nobody picks it up.

**Comment by falkTX** [comment]
We know of it, quite nice set.
It is already mentioned in https://github.com/DISTRHO/Cardinal/wiki/Possible-modules-to-include so there is no need for a dedicated ticket for it.

**Comment by trevormeier** [comment]
Yes! I would be very excited to use the Surge modules in Cardinal.

**Comment by Cardinny** [comment]
Just adding my two cents that I would love to have this. It allows you to control the configuration of surge in a way that is not possible in the plugin.

**Comment by RCJacH** [comment]
I tried adding the module following the guideline [here](https://github.com/DISTRHO/Cardinal/discussions/28#discussioncomment-1544543), but I don't know what I wrote work or not, since I'm having trouble building on docker due to error with other modules, and I don't know enough C++ to debug it.

Should I make a PR to start a dedicated discussion over there?

**Comment by falkTX** [comment]
before even starting, we need to handle the dependencies from surgext first, with common libraries needing to be made optional on its vendoring (that is, use system libs if linux/macos packager requests it)

surge has quite a few dependencies, so this is already going to take quite a lot of time.

then there is the need to ensure there are no symbol conflicts, easily done by doing a fresh build with LTO enabled.
we might hit github actions time limit on this, and if so it becomes a blocker.

after those 2 are handled, then we can finally add surge xt. how to deal with dark/light mode switch is to be defined.

PS: the building options are documented in https://github.com/DISTRHO/Cardinal/blob/main/docs/BUILDING.md

**Comment by falkTX** [comment]
and actually, I am reopening this ticket since it is likely there will be more requests for the same.
surge xt is an awesome module collection, would be great to have them.
but we might hit the limit of what we can build for free on github. and there was interest to add rebeltech too..

here is a basic todo list:
- [ ] list all surge-xt dependencies and how to build them
- [ ] add all dependencies as vendored in Cardinal (see `deps/Makefile` for how others are handled)
- [ ] make those dependencies possible to build as system libraries instead of vendored (as many as possible)
- [ ] check that everything builds for Linux, BSD, macOS, Windows and web-assembly (minimum)
- [ ] ensure there are no symbol conflicts (LTO can help here, maybe only enabled on Linux builds going forward?)
- [ ] finally add surge-xt modules to the collection

**Comment by falkTX** [comment]
surgext has been now added, will be available in the next builds and 22.12 release
