### ISSUE TITLE
Search modules keyboard input produces duplicate of input key

### ISSUE THREAD

**Issue by jp-gorman** [DISTRHO/Cardinal#54]
Version Tested: SHA builld - 4a85fc8

Expected:
Rick click to open dialog for adding module
Type "a" to see all modules starting with "a"

Actual:
Type "a" and get "aa". 

Just FYI - I confirmed double lettering was not happening on Rack2 official release.

**Comment by falkTX** [comment]
This is on Windows, correct?

**Comment by jp-gorman** [comment]
OSX 10.15.6 - Reaper 6.19 64bit vst and vsti versions.

**Comment by AriaSalvatrice** [comment]
Keyboard input in Windows is host-dependent with a variety of weird behaviors.

So far:
- **Reason 11**: Behaves as if the Shift key were stuck, only uppercase and no spaces
- **Renoise**: Won't accept keyboard input even after the keyboard is explicitly enabled in renoise's ui
- **VSTHost**: Text fields add a letter on key down and on key up both

**Comment by falkTX** [comment]
To explain, this is because VST2 defines a method for hosts to notify plugins of keyboard events.
But typical of things in VST, exactly how to implement is not documented well so every host does it a bit differently.

Some hosts do not send the special VST2 keycodes at all, only relying on native OS events.
Others send both.
And finally a few ones only send VST2 keycodes, never OS events.

The whole thing is quite silly and PITA to implement and get right...

**Comment by garygeeg** [comment]
Can happens in Reaper on Windows for me but Ableton is fine.
