### ISSUE TITLE
X scroll - if it's not broken, don't fix it

### ISSUE THREAD

**Issue by iamdannywyatt** [DISTRHO/Cardinal#582]
Why changing the behavior of the scroll if 
1 - An option to invert it back to what it used to be isn't available?
2 - The current direction makes no sense:
     When scrolling DOWN, the patch goes UP
     When scrolling RIGHT, the patch goes RIGHT

If it's inverted, then **everything** should be inverted:
Scroll down, things go down
Scroll right, things go right

At the same time, offer the option to customize this behavior. Not everyone works the same way...
Going back to version 23.02 because this scrolling thing is counterproductive.

If it's not broken, don't "fix" it.

**Comment by falkTX** [comment]
the problem comes from pugl, something is not quite right. but under some platforms it works correctly.
if you use https://cardinal.kx.studio/live under macOS, the scrolling works in a consistent way.
I believe under Linux it also scrolls consistently, it is only under macOS native that it does not.

Also, if we change macOS setting for "natural scrolling", the behaviour in Cardinal changes to the inverse too.

So from my tests on different OSes I think we want the X inverted scroll, just not for macOS native.

**Comment by iamdannywyatt** [comment]
"_the problem comes from pugl_"
Don't know what that means, as I'm not a developer

Yes, the web version works as expected

Can't you add a menu option to invert the X scroll then?

**Comment by falkTX** [comment]
no need, it "just" needs proper fixing.

I confirmed yesterday that Linux scrolling works fine too, so it is really only on macOS that is problematic.

(and pugl is the underlying library to handle window management and events, issue comes from there yes)

**Comment by falkTX** [comment]
Fixed in 23.10 release

**Comment by iamdannywyatt** [comment]
@falkTX thanks!
