### ISSUE TITLE
[Feature Request] Include Airwin2Rack By BaconPaul

### ISSUE THREAD

**Issue by Grupletruge** [DISTRHO/Cardinal#683]
### Description

I apologize if this is an improper usage of the request! I kind of figured because BaconPauls stuff was all included and Airwin2rack was on the possible modules list that'd be around rather soon, but its been awhile now. Theres SO MUCH stuff in there that i've been dying to use in Cardinal. I partially ask because if its not on the itinerary i may go as far as to learn and do myself.

**Comment by dromer** [comment]
The list of possible modules to include is not organized by priority, but simply to show the "possibility" of including them (mainly based on licensing and other qualities).

It is not on the planning this year to add any more features to Cardinal as the team does not have much time.
Only bugfixes and general updates may get some attention.

So if you want to find out [how to add modules](https://github.com/DISTRHO/Cardinal/discussions/28) yourself that would be a better strategy than to ask and wait.

Indeed it's bit improper usage of the ticketing system as we explicitly have the wiki page for keeping track of possible modules to include.

**Comment by washikano** [comment]
Hi, if you'd like to try your hand at porting the module, you can follow [this example](https://github.com/DISTRHO/Cardinal/discussions/28); check out the building instructions [here](https://github.com/DISTRHO/Cardinal/blob/main/docs/BUILDING.md) (NOTE: you can't build locally on Windows, you'll need a Unix-based or Unix-like OS)

The list is not a guarantee that the modules will be added by the maintainers since there are other priorities like bug fixing and updating current modules over adding more modules (besides, they lead busy lives and don't work exclusively on Cardinal); it's only used to track which modules can and can't be added

But if you make a PR a maintainer will eventually take a look ^^ start by forking the repo and clone locally, and follow the directions linked above
